# This is a sample aws-auth-patch.yml file. 
# Actual aws-auth-patch.yml will be created at /System/Volumes/Data/private/tmp/aws-auth-patch.yml path.

apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::524632144598:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-9327MLNWXQV3
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::524632144598:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-09-17T14:46:08Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1400"
  uid: 7d7e6e8e-32b0-46fd-7baa-a113e7a49be3
